image: Visual Studio 2019 Preview

branches:
  only:
  - master

version: 5.0.{build}

init:
  - cmd: git config --global core.autocrlf true

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: $(appveyor_build_version)
  package_version: $(appveyor_build_version)
  assembly_version: $(appveyor_build_version)
  file_version: $(appveyor_build_version)
  informational_version: $(appveyor_build_version)

before_build:
  - cmd: dotnet --version
  - cmd: nuget restore "./Nami.sln"
  - cmd: dotnet restore ./Nami/Nami.csproj --verbosity m

clone_depth: 1

test_script:
  - cmd: dotnet restore ./Nami.Tests/Nami.Tests.csproj --verbosity m
  - cmd: cd Nami.Tests
  - cmd: dotnet test

on_success:
  - ps: Invoke-RestMethod https://raw.githubusercontent.com/DiscordHooks/appveyor-discord-webhook/master/send.ps1 -o send.ps1
  - ps: ./send.ps1 success $env:WEBHOOK_URL
on_failure:
  - ps: Invoke-RestMethod https://raw.githubusercontent.com/DiscordHooks/appveyor-discord-webhook/master/send.ps1 -o send.ps1
  - ps: ./send.ps1 failure $env:WEBHOOK_URL

deploy: off
